# This file is required for demo auto configuration

demo.database.port: 9005
demo.database.realPort: 9005
storefront.jvm.options: --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.naming/com.sun.jndi.ldap=ALL-UNNAMED -XX:StartFlightRecording=duration=60s,name=MyRecording,filename=myrecording.jfr,settings=profile
