# This file is required for demo auto configuration

demo.database.port: 9005
demo.database.realPort: 9006

loadgen.users: 20

storefront.jvm.options: -XX:StartFlightRecording=duration=60s,name=MyRecording,filename=myrecording.jfr,settings=profile

common.jvm.options: --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.naming/com.sun.jndi.ldap=ALL-UNNAMED
