<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.mycompany-community</groupId>
        <artifactId>boot-community-demo</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>boot-community-demo-site</artifactId>
    <packaging>jar</packaging>

    <name>Community Demo Site</name>
    <description>Web Module For Customized Broadleaf Commerce Site</description>

    <properties>
        <debug.port>8000</debug.port>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.mycompany-community</groupId>
            <artifactId>boot-community-demo-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.broadleafcommerce</groupId>
            <artifactId>broadleaf-framework-web</artifactId>
        </dependency>
        <!-- Provided by perf
        <dependency>
            <groupId>com.broadleafcommerce</groupId>
            <artifactId>broadleaf-boot-starter-solr</artifactId>
        </dependency>
        <dependency>
            <groupId>com.broadleafcommerce</groupId>
            <artifactId>broadleaf-boot-starter-hsql-database</artifactId>
        </dependency>
         -->
        <dependency>
            <groupId>org.broadleafcommerce</groupId>
            <artifactId>broadleaf-thymeleaf3-presentation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.zhanhb</groupId>
            <artifactId>thymeleaf-layout-dialect</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>ROOT</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
              <groupId>com.google.cloud.tools</groupId>
              <artifactId>jib-maven-plugin</artifactId>
              <configuration>
                <container>
                  <mainClass>com.community.SiteApplication</mainClass>
                  <jvmFlags>
                    <jvmFlag>-DlifeGrant.port=23045</jvmFlag> <!-- port should be exposed from container for lifeGrant to work -->
                    <jvmFlag>-Djava.rmi.server.hostname=127.2.2.2</jvmFlag> <!-- Mess with RMI IP -->
                    <jvmFlag>--add-opens</jvmFlag><jvmFlag>java.base/java.lang=ALL-UNNAMED</jvmFlag>
                    <jvmFlag>--add-opens</jvmFlag><jvmFlag>java.base/java.util=ALL-UNNAMED</jvmFlag>
                    <jvmFlag>--add-opens</jvmFlag><jvmFlag>java.base/jdk.internal.ref=ALL-UNNAMED</jvmFlag>
                    <jvmFlag>--add-opens</jvmFlag><jvmFlag>java.naming/com.sun.jndi.ldap=ALL-UNNAMED</jvmFlag>
                  </jvmFlags>
                  <!-- <expandClasspathDependencies>true</expandClasspathDependencies> -->
                  <workingDirectory>/app/</workingDirectory>
                </container>
                <extraDirectories>
                  <paths>
                    <path>
                      <from>../</from>
                      <into>/app/</into>
                      <includes>demo.properties</includes>
                    </path>
                    <path>
                      <from>etc/</from>
                      <into>/app/</into>
                      <includes>*.properties</includes>
                    </path>
                  </paths>
                </extraDirectories>
                <from>
                  <image>eclipse-temurin:17</image>
                </from>
             </configuration>
           </plugin>
        </plugins>
    </build>

    <profiles>
      <profile>
        <id>build_image</id>
        <build>
          <plugins>
            <plugin>
              <groupId>com.google.cloud.tools</groupId>
              <artifactId>jib-maven-plugin</artifactId>
              <executions>
                <execution>
                  <id>build-tar</id>
                  <phase>compile</phase>
                  <goals>
                    <goal>dockerBuild</goal>
                  </goals>
                </execution>
              </executions>

            </plugin>
          </plugins>
        </build>
      </profile>
    </profiles>

</project>
