demo.database.host: host.docker.internal
solr.server.host: host.docker.internal

solr.url.primary=http://host.docker.internal:8983/solr/catalog
solr.url.reindex=http://host.docker.internal:8983/solr/catalog_reindex
solr.url.admin=http://host.docker.internal:8983/solr
